### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by toketin** [Pinperepette/IPTV#12]
Hi, under Arch with dependency python-pyqt4 installed i get:

python iptv_cli.py
  File "iptv_cli.py", line 14
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'

May it be due to the python's version used by the system?

**Comment by toketin** [comment]
Different error using python2:
python2 iptv_cli.py   
Traceback (most recent call last):
  File "iptv_cli.py", line 2, in <module>
    import Crawler
  File "/home/marco/IPTV/iptv/Crawler.py", line 2, in <module>
    import google
ImportError: No module named google

**Comment by Pinperepette** [comment]
run pip install -r requirements.txt in order to get the full dependencies

**Comment by Pinperepette** [comment]
sudo pip install google

2016-01-03 13:25 GMT+01:00 Marco Londero <notifications@github.com>:

> Different error using python2:
> python2 iptv_cli.py
>
> Traceback (most recent call last):
> File "iptv_cli.py", line 2, in
> import Crawler
> File "/home/marco/IPTV/iptv/Crawler.py", line 2, in
> import google
> ImportError: No module named google
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pinperepette/IPTV/issues/12#issuecomment-168493914>.
>



-- 
I-I4ckeI2 ®
*Security Researcher*

"Voi potete fermare questo individuo, ma non potete fermarci tutti ... dopo
tutto, siamo tutti uguali."

http://pinperepette.it <http://pinperepette.it/info/>  *puoi contattarmi
anche a* pirata@pinperepette.it

**Comment by Tonyrock90** [comment]
salve, sapete come posso risolvere?
tony@System:~/Scrivania/IPTV-master/iptv$ ls
Crawler.py  iptv.py  languages  output  requirements.txt
tony@System:~/Scrivania/IPTV-master/iptv$ pip install -r requirements.txt
Downloading/unpacking pyprind==2.9.3 (from -r requirements.txt (line 1))
  Downloading PyPrind-2.9.3.zip
  Running setup.py (path:/tmp/pip_build_tony/pyprind/setup.py) egg_info for package pyprind
    
Downloading/unpacking google==1.7 (from -r requirements.txt (line 2))
  Downloading google-1.7-py2-none-any.whl
Downloading/unpacking psutil==3.3.0 (from -r requirements.txt (line 3))
  Downloading psutil-3.3.0.tar.gz (261kB): 261kB downloaded
  Running setup.py (path:/tmp/pip_build_tony/psutil/setup.py) egg_info for package psutil
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: manifest_maker: MANIFEST.in, line 18: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
Downloading/unpacking clint==0.5.1 (from -r requirements.txt (line 4))
  Downloading clint-0.5.1.tar.gz
  Running setup.py (path:/tmp/pip_build_tony/clint/setup.py) egg_info for package clint
    
    warning: no files found matching 'recursive-include'
    warning: no files found matching 'docs'
Downloading/unpacking colored==1.2.1 (from -r requirements.txt (line 5))
  Downloading colored-1.2.1.tar.gz
  Running setup.py (path:/tmp/pip_build_tony/colored/setup.py) egg_info for package colored
    
Downloading/unpacking tqdm==3.4.0 (from -r requirements.txt (line 6))
  Downloading tqdm-3.4.0-py2.py3-none-any.whl
Downloading/unpacking beautifulsoup4 (from google==1.7->-r requirements.txt (line 2))
  Downloading beautifulsoup4-4.4.1-py2-none-any.whl (81kB): 81kB downloaded
Downloading/unpacking args (from clint==0.5.1->-r requirements.txt (line 4))
  Downloading args-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip_build_tony/args/setup.py) egg_info for package args
    
Installing collected packages: pyprind, google, psutil, clint, colored, tqdm, beautifulsoup4, args
  Running setup.py install for pyprind
    error: could not create '/usr/local/lib/python2.7/dist-packages/pyprind': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_tony/pyprind/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TLvCSi-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-i686-2.7

creating build/lib.linux-i686-2.7/pyprind

copying pyprind/prog_class.py -> build/lib.linux-i686-2.7/pyprind

copying pyprind/__init__.py -> build/lib.linux-i686-2.7/pyprind

copying pyprind/generator_factory.py -> build/lib.linux-i686-2.7/pyprind

copying pyprind/progbar.py -> build/lib.linux-i686-2.7/pyprind

copying pyprind/progpercent.py -> build/lib.linux-i686-2.7/pyprind

running install_lib

creating /usr/local/lib/python2.7/dist-packages/pyprind

error: could not create '/usr/local/lib/python2.7/dist-packages/pyprind': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_tony/pyprind/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TLvCSi-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_tony/pyprind
Storing debug log for failure in /home/tony/.pip/pip.log
