### ISSUE TITLE
Parameter -pl thrown exception

### ISSUE THREAD

**Issue by ludo237** [Pinperepette/IPTV#2]
It seems like the script is not able to find the `search module`

Steps to reproduce

* Open shell
* type  `python iptv.py -pl`

```Python

Traceback (most recent call last):
  File "iptv.py", line 82, in <module>
    print_link()
  File "iptv.py", line 38, in print_link
    for url in google.search(ricerca, num=30, stop=1):
AttributeError: 'module' object has no attribute 'search'

```

**Comment by gigitux** [comment]
This script is write in python 2. You run it with python 3.
Try with

python2 iptv.py -pl

**Comment by ludo237** [comment]
@gigitux Got the same error. I'm on OSX using Brew for python2 and python3

**Comment by gigitux** [comment]
@ludo237 I don't know. I use this script on a distro GNU/Linux.
If I'm not wrong @Pinperepette use OSX

**Comment by Pinperepette** [comment]
@ludo237 @gigitux yep use osx :)

**Comment by Pinperepette** [comment]
@ludo237 @gigitux because we are Italian and write in English ? LOL

**Comment by ludo237** [comment]
@Pinperepette @gigitux cuz is cool :sunglasses:

**Comment by paciops** [comment]
@Pinperepette why* ahah

**Comment by Pinperepette** [comment]
mannaia la puttana :)

**Comment by gigitux** [comment]
HAHAAHAHAH
Giusto per fare un po' i fighi :D
